[package]
name = "notify-rust"
version = "3.4.1"
authors = ["Hendrik Sollich <hendrik@hoodie.de>", "panicbit <panicbit@users.noreply.github.com>"]
description = "Show desktop notifications. Pure Rust dbus client and server."
homepage = "https://github.com/hoodie/notify-rust"
repository = "https://github.com/hoodie/notify-rust"
documentation = "https://docs.rs/notify-rust/"

license = "MIT/Apache-2.0"
keywords = ["desktop", "notification", "notify", "dbus", "libnotify"]
readme = "README.md"

include = [
  "History.md",
  ".gitignore",
  ".travis.yml",
  "Cargo.toml",
  "src/*.rs",
  "tests/*.rs"
]

[dependencies]
error-chain = "0.10"

[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies]
dbus = "~0.4"
lazy_static = {version = "0.2", optional = true}
image = {version = "0.13", optional = true}

[target.'cfg(target_os="macos")'.dependencies]
mac-notification-sys = "0.1"

[target.'cfg(target_os="windows")'.dependencies]
winrt-notification = "0.2.1"

[features]
default = []
images = ["image", "lazy_static"]
